import type { Job, JobStatus, TimelineEntry, ActivityEntry } from './types'
import { emptyQA } from './types'

function makeTimeline(statuses: JobStatus[], startDaysAgo: number = 60): TimelineEntry[] {
  const timeline: TimelineEntry[] = []
  let offset = startDaysAgo
  for (const s of statuses) {
    const d = new Date()
    d.setDate(d.getDate() - offset)
    timeline.push({
      status: s,
      date: d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }),
      time: d.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', hour12: true }),
      timestamp: d.getTime(),
    })
    offset -= 5 + Math.floor(Math.random() * 10)
  }
  return timeline
}

function dateStr(daysAgo: number): string {
  const d = new Date()
  d.setDate(d.getDate() - daysAgo)
  return d.toISOString().split('T')[0]
}

function ts(daysAgo: number): number {
  const d = new Date()
  d.setDate(d.getDate() - daysAgo)
  return d.getTime()
}

function addActivity(jobName: string, type: ActivityEntry['type'], message: string, daysAgo: number): ActivityEntry {
  return { id: crypto.randomUUID(), type, message: message.replace('{company}', jobName), timestamp: ts(daysAgo) }
}

// ─── WISHLIST (5) ─────────────────────────────────────────────────
const w1: Job = { id: crypto.randomUUID(), company: 'NVIDIA', role: 'AI Test Engineer', linkedinUrl: 'https://linkedin.com/jobs/nvidia-ai-test', resume: 'ai_test_engineer.pdf', dateApplied: dateStr(1), salaryRange: '$160k - $200k', notes: 'Cutting edge AI company, would love to work here', status: 'wishlist', priority: 'urgent', timeline: makeTimeline(['wishlist'], 1), interviews: [], qa: { ...emptyQA(), recruiterName: 'David Park', recruiterEmail: 'david.p@nvidia.com', applicationSource: 'linkedin', expectedSalary: '$180k' }, activities: [addActivity('NVIDIA', 'added', 'Added NVIDIA - AI Test Engineer to wishlist', 1)], createdAt: ts(1), updatedAt: ts(1) }
const w2: Job = { id: crypto.randomUUID(), company: 'Stripe', role: 'SDET', linkedinUrl: 'https://linkedin.com/jobs/stripe-sdet', resume: 'sdet_profile_2026.pdf', dateApplied: dateStr(2), salaryRange: '$150k - $190k', notes: 'Great fintech company, strong engineering culture', status: 'wishlist', priority: 'high', timeline: makeTimeline(['wishlist'], 2), interviews: [], qa: { ...emptyQA(), recruiterName: 'Lisa Wang', recruiterEmail: 'lisa.w@stripe.com', applicationSource: 'company_website', expectedSalary: '$170k' }, activities: [addActivity('Stripe', 'added', 'Added Stripe - SDET to wishlist', 2)], createdAt: ts(2), updatedAt: ts(2) }
const w3: Job = { id: crypto.randomUUID(), company: 'ServiceNow', role: 'Performance Tester', linkedinUrl: 'https://linkedin.com/jobs/servicenow-perf', resume: 'performance_testing.pdf', dateApplied: dateStr(4), salaryRange: '$120k - $155k', notes: 'Good work-life balance, cloud platform company', status: 'wishlist', priority: 'medium', timeline: makeTimeline(['wishlist'], 4), interviews: [], qa: { ...emptyQA(), recruiterName: 'Raj Patel', recruiterEmail: 'raj.p@servicenow.com', applicationSource: 'linkedin', expectedSalary: '$140k' }, activities: [addActivity('ServiceNow', 'added', 'Added ServiceNow - Performance Tester to wishlist', 4)], createdAt: ts(4), updatedAt: ts(4) }
const w4: Job = { id: crypto.randomUUID(), company: 'Airbnb', role: 'QA Lead', linkedinUrl: 'https://linkedin.com/jobs/airbnb-qa-lead', resume: 'lead_qa_resume.pdf', dateApplied: dateStr(5), salaryRange: '$170k - $210k', notes: 'Amazing company culture, remote-friendly', status: 'wishlist', priority: 'high', timeline: makeTimeline(['wishlist'], 5), interviews: [], qa: { ...emptyQA(), recruiterName: 'Mia Johnson', recruiterEmail: 'mia.j@airbnb.com', applicationSource: 'referral', referralName: 'Alex Chen', expectedSalary: '$190k' }, activities: [addActivity('Airbnb', 'added', 'Added Airbnb - QA Lead to wishlist', 5)], createdAt: ts(5), updatedAt: ts(5) }
const w5: Job = { id: crypto.randomUUID(), company: 'Freshworks', role: 'Automation Tester', linkedinUrl: 'https://linkedin.com/jobs/freshworks-auto', resume: 'automation_tester.pdf', dateApplied: dateStr(3), salaryRange: '$80k - $110k', notes: 'Growing SaaS company from India', status: 'wishlist', priority: 'low', timeline: makeTimeline(['wishlist'], 3), interviews: [], qa: { ...emptyQA(), recruiterName: 'Kavya Nair', recruiterEmail: 'kavya.n@freshworks.com', applicationSource: 'naukri', expectedSalary: '$95k' }, activities: [addActivity('Freshworks', 'added', 'Added Freshworks - Automation Tester to wishlist', 3)], createdAt: ts(3), updatedAt: ts(3) }

// ─── APPLIED (6) ──────────────────────────────────────────────────
const a1: Job = { id: crypto.randomUUID(), company: 'Google', role: 'QA Engineer', linkedinUrl: 'https://linkedin.com/jobs/google-qa', resume: 'qa_resume_v3.pdf', dateApplied: dateStr(10), salaryRange: '$140k - $180k', notes: 'Applied through Google careers portal. Referral from John.', status: 'applied', priority: 'urgent', timeline: makeTimeline(['applied'], 10), interviews: [], qa: { ...emptyQA(), recruiterName: 'Sundar Rajan', recruiterEmail: 'sundar.r@google.com', applicationSource: 'company_website', referralName: 'John M.', expectedSalary: '$160k', nextFollowUpDate: dateStr(5) }, activities: [addActivity('Google', 'added', 'Added Google - QA Engineer', 10)], createdAt: ts(15), updatedAt: ts(10) }
const a2: Job = { id: crypto.randomUUID(), company: 'Microsoft', role: 'Senior QA Engineer', linkedinUrl: 'https://linkedin.com/jobs/microsoft-senior-qa', resume: 'sdet_profile_2026.pdf', dateApplied: dateStr(12), salaryRange: '$150k - $195k', notes: 'Applied via LinkedIn Easy Apply', status: 'applied', priority: 'high', timeline: makeTimeline(['applied'], 12), interviews: [], qa: { ...emptyQA(), recruiterName: 'Amy Li', recruiterEmail: 'amy.li@microsoft.com', applicationSource: 'linkedin', expectedSalary: '$175k', nextFollowUpDate: dateStr(3) }, activities: [addActivity('Microsoft', 'added', 'Added Microsoft - Senior QA Engineer', 12)], createdAt: ts(18), updatedAt: ts(12) }
const a3: Job = { id: crypto.randomUUID(), company: 'Cisco', role: 'API Tester', linkedinUrl: 'https://linkedin.com/jobs/cisco-api', resume: 'automation_tester.pdf', dateApplied: dateStr(8), salaryRange: '$110k - $145k', notes: 'Good networking company, applied through company website', status: 'applied', priority: 'medium', timeline: makeTimeline(['applied'], 8), interviews: [], qa: { ...emptyQA(), recruiterName: 'Tom Harris', recruiterEmail: 'tom.h@cisco.com', applicationSource: 'company_website', expectedSalary: '$130k', nextFollowUpDate: dateStr(2) }, activities: [addActivity('Cisco', 'added', 'Added Cisco - API Tester', 8)], createdAt: ts(12), updatedAt: ts(8) }
const a4: Job = { id: crypto.randomUUID(), company: 'Intel', role: 'Manual Tester', linkedinUrl: 'https://linkedin.com/jobs/intel-manual', resume: 'qa_resume_v3.pdf', dateApplied: dateStr(15), salaryRange: '$95k - $125k', notes: 'Hardware + software testing role', status: 'applied', priority: 'medium', timeline: makeTimeline(['applied'], 15), interviews: [], qa: { ...emptyQA(), recruiterName: 'Jennifer Kim', recruiterEmail: 'jen.kim@intel.com', applicationSource: 'indeed', expectedSalary: '$110k', nextFollowUpDate: dateStr(7) }, activities: [addActivity('Intel', 'added', 'Added Intel - Manual Tester', 15)], createdAt: ts(20), updatedAt: ts(15) }
const a5: Job = { id: crypto.randomUUID(), company: 'IBM', role: 'QA Lead', linkedinUrl: 'https://linkedin.com/jobs/ibm-qa-lead', resume: 'lead_qa_resume.pdf', dateApplied: dateStr(6), salaryRange: '$125k - $160k', notes: 'Enterprise AI focus', status: 'applied', priority: 'high', timeline: makeTimeline(['applied'], 6), interviews: [], qa: { ...emptyQA(), recruiterName: 'Robert Chen', recruiterEmail: 'robert.c@ibm.com', applicationSource: 'linkedin', expectedSalary: '$145k', nextFollowUpDate: dateStr(1) }, activities: [addActivity('IBM', 'added', 'Added IBM - QA Lead', 6)], createdAt: ts(10), updatedAt: ts(6) }
const a6: Job = { id: crypto.randomUUID(), company: 'TCS', role: 'Automation Tester', linkedinUrl: 'https://linkedin.com/jobs/tcs-auto', resume: 'automation_tester.pdf', dateApplied: dateStr(9), salaryRange: '$70k - $95k', notes: 'Consulting role - onsite opportunity', status: 'applied', priority: 'low', timeline: makeTimeline(['applied'], 9), interviews: [], qa: { ...emptyQA(), recruiterName: 'Priya Sharma', recruiterEmail: 'priya.s@tcs.com', applicationSource: 'naukri', expectedSalary: '$85k', nextFollowUpDate: dateStr(4) }, activities: [addActivity('TCS', 'added', 'Added TCS - Automation Tester', 9)], createdAt: ts(14), updatedAt: ts(9) }

// ─── FOLLOW-UP (4) ────────────────────────────────────────────────
const f1: Job = { id: crypto.randomUUID(), company: 'Amazon', role: 'SDET', linkedinUrl: 'https://linkedin.com/jobs/amazon-sdet', resume: 'sdet_profile_2026.pdf', dateApplied: dateStr(20), salaryRange: '$160k - $210k', notes: 'Followed up twice. Recruiter said they are reviewing.', status: 'follow-up', priority: 'urgent', timeline: makeTimeline(['applied', 'follow-up'], 25), interviews: [], qa: { ...emptyQA(), recruiterName: 'Rachel Green', recruiterEmail: 'rachel.g@amazon.com', applicationSource: 'linkedin', expectedSalary: '$185k', nextFollowUpDate: dateStr(2) }, activities: [addActivity('Amazon', 'added', 'Added Amazon - SDET', 25), addActivity('Amazon', 'moved', 'Moved Amazon to Follow-up', 20)], createdAt: ts(35), updatedAt: ts(20) }
const f2: Job = { id: crypto.randomUUID(), company: 'Oracle', role: 'QA Engineer', linkedinUrl: 'https://linkedin.com/jobs/oracle-qa', resume: 'qa_resume_v3.pdf', dateApplied: dateStr(22), salaryRange: '$120k - $155k', notes: 'Followed up, waiting for tech screen schedule', status: 'follow-up', priority: 'high', timeline: makeTimeline(['applied', 'follow-up'], 28), interviews: [], qa: { ...emptyQA(), recruiterName: 'Sarah Johnson', recruiterEmail: 'sarah.j@oracle.com', applicationSource: 'company_website', expectedSalary: '$140k', nextFollowUpDate: dateStr(5) }, activities: [addActivity('Oracle', 'added', 'Added Oracle - QA Engineer', 28), addActivity('Oracle', 'moved', 'Moved Oracle to Follow-up', 22)], createdAt: ts(35), updatedAt: ts(22) }
const f3: Job = { id: crypto.randomUUID(), company: 'PayPal', role: 'Playwright Engineer', linkedinUrl: 'https://linkedin.com/jobs/paypal-playwright', resume: 'automation_tester.pdf', dateApplied: dateStr(18), salaryRange: '$130k - $165k', notes: 'Sent follow-up email last week', status: 'follow-up', priority: 'high', timeline: makeTimeline(['applied', 'follow-up'], 22), interviews: [], qa: { ...emptyQA(), recruiterName: 'Mike Chen', recruiterEmail: 'mike.c@paypal.com', applicationSource: 'referral', referralName: 'Anita K.', expectedSalary: '$150k', nextFollowUpDate: dateStr(3) }, activities: [addActivity('PayPal', 'added', 'Added PayPal - Playwright Engineer', 22), addActivity('PayPal', 'moved', 'Moved PayPal to Follow-up', 18)], createdAt: ts(28), updatedAt: ts(18) }
const f4: Job = { id: crypto.randomUUID(), company: 'Uber', role: 'Performance Tester', linkedinUrl: 'https://linkedin.com/jobs/uber-perf', resume: 'performance_testing.pdf', dateApplied: dateStr(25), salaryRange: '$145k - $185k', notes: 'Recruiter reached out after follow-up', status: 'follow-up', priority: 'medium', timeline: makeTimeline(['applied', 'follow-up'], 30), interviews: [], qa: { ...emptyQA(), recruiterName: 'Alex Thompson', recruiterEmail: 'alex.t@uber.com', applicationSource: 'linkedin', expectedSalary: '$165k', nextFollowUpDate: dateStr(4) }, activities: [addActivity('Uber', 'added', 'Added Uber - Performance Tester', 30), addActivity('Uber', 'moved', 'Moved Uber to Follow-up', 25)], createdAt: ts(35), updatedAt: ts(25) }

// ─── INTERVIEW (4) ────────────────────────────────────────────────
const i1: Job = { id: crypto.randomUUID(), company: 'Apple', role: 'QA Lead', linkedinUrl: 'https://linkedin.com/jobs/apple-qa-lead', resume: 'lead_qa_resume.pdf', dateApplied: dateStr(35), salaryRange: '$170k - $220k', notes: 'HR round completed. Technical round 1 scheduled.', status: 'interview', priority: 'urgent', timeline: makeTimeline(['applied', 'follow-up', 'interview'], 40), interviews: [{ id: crypto.randomUUID(), date: dateStr(28), time: '10:00 AM', mode: 'online', meetingLink: 'https://apple.hr.round/jane', interviewerName: 'Jane Smith', round: 'hr', notes: 'HR screening - went well' }, { id: crypto.randomUUID(), date: dateStr(20), time: '02:00 PM', mode: 'online', meetingLink: 'https://apple.tech1/jane', interviewerName: 'Mike Brown', round: 'technical', notes: 'Technical Round 1 - System design questions' }, { id: crypto.randomUUID(), date: dateStr(15), time: '11:00 AM', mode: 'online', meetingLink: 'https://apple.tech2/jane', interviewerName: 'Sarah Wilson', round: 'technical', notes: 'Technical Round 2 - Automation frameworks' }], qa: { ...emptyQA(), recruiterName: 'Jane Smith', recruiterEmail: 'jane.s@apple.com', applicationSource: 'linkedin', expectedSalary: '$195k', nextFollowUpDate: dateStr(10) }, activities: [addActivity('Apple', 'added', 'Added Apple - QA Lead', 40), addActivity('Apple', 'moved', 'Moved Apple to Follow-up', 35), addActivity('Apple', 'moved', 'Moved Apple to Interview', 28), addActivity('Apple', 'interview', 'HR round completed for Apple', 28)], createdAt: ts(50), updatedAt: ts(15) }
const i2: Job = { id: crypto.randomUUID(), company: 'Meta', role: 'SDET', linkedinUrl: 'https://linkedin.com/jobs/meta-sdet', resume: 'sdet_profile_2026.pdf', dateApplied: dateStr(30), salaryRange: '$175k - $225k', notes: 'Manager round cleared. Final round scheduled.', status: 'interview', priority: 'urgent', timeline: makeTimeline(['applied', 'follow-up', 'interview'], 35), interviews: [{ id: crypto.randomUUID(), date: dateStr(25), time: '11:30 AM', mode: 'online', meetingLink: 'https://meta.hr/round', interviewerName: 'Chris Lee', round: 'hr', notes: 'HR interview - compensation discussed' }, { id: crypto.randomUUID(), date: dateStr(20), time: '01:00 PM', mode: 'online', meetingLink: 'https://meta.tech/round', interviewerName: 'Emily Davis', round: 'technical', notes: 'Technical - Coding and algorithms' }, { id: crypto.randomUUID(), date: dateStr(16), time: '03:00 PM', mode: 'online', meetingLink: 'https://meta.mgr/round', interviewerName: 'David Kim', round: 'manager', notes: 'Manager round - team fit and leadership' }], qa: { ...emptyQA(), recruiterName: 'Chris Lee', recruiterEmail: 'chris.l@meta.com', applicationSource: 'referral', referralName: 'Mark Z', expectedSalary: '$200k', nextFollowUpDate: dateStr(8) }, activities: [addActivity('Meta', 'added', 'Added Meta - SDET', 35), addActivity('Meta', 'moved', 'Moved Meta to Follow-up', 30), addActivity('Meta', 'moved', 'Moved Meta to Interview', 25), addActivity('Meta', 'interview', 'Manager round passed for Meta', 16)], createdAt: ts(45), updatedAt: ts(16) }
const i3: Job = { id: crypto.randomUUID(), company: 'Atlassian', role: 'Cypress Engineer', linkedinUrl: 'https://linkedin.com/jobs/atlassian-cypress', resume: 'automation_tester.pdf', dateApplied: dateStr(28), salaryRange: '$130k - $170k', notes: 'First technical round done. Waiting for result.', status: 'interview', priority: 'high', timeline: makeTimeline(['applied', 'follow-up', 'interview'], 32), interviews: [{ id: crypto.randomUUID(), date: dateStr(22), time: '09:00 AM', mode: 'online', meetingLink: 'https://atlassian.hr/round', interviewerName: 'Nina Patel', round: 'hr', notes: 'HR round - discussed role and team' }, { id: crypto.randomUUID(), date: dateStr(18), time: '02:30 PM', mode: 'online', meetingLink: 'https://atlassian.tech/round', interviewerName: 'Tom Cruise', round: 'technical', notes: 'Technical - Cypress and Playwright expertise' }], qa: { ...emptyQA(), recruiterName: 'Nina Patel', recruiterEmail: 'nina.p@atlassian.com', applicationSource: 'linkedin', expectedSalary: '$155k', nextFollowUpDate: dateStr(5) }, activities: [addActivity('Atlassian', 'added', 'Added Atlassian - Cypress Engineer', 32), addActivity('Atlassian', 'moved', 'Moved Atlassian to Interview', 22)], createdAt: ts(40), updatedAt: ts(18) }
const i4: Job = { id: crypto.randomUUID(), company: 'LinkedIn', role: 'API Tester', linkedinUrl: 'https://linkedin.com/jobs/linkedin-api', resume: 'qa_resume_v3.pdf', dateApplied: dateStr(32), salaryRange: '$140k - $180k', notes: 'HR round cleared. Technical scheduled for next week.', status: 'interview', priority: 'high', timeline: makeTimeline(['applied', 'follow-up', 'interview'], 38), interviews: [{ id: crypto.randomUUID(), date: dateStr(26), time: '10:30 AM', mode: 'online', meetingLink: 'https://linkedin.hr/round', interviewerName: 'Hannah Lee', round: 'hr', notes: 'HR screening - positive feedback' }, { id: crypto.randomUUID(), date: dateStr(20), time: '01:00 PM', mode: 'online', meetingLink: 'https://linkedin.tech/round', interviewerName: 'Steve Park', round: 'technical', notes: 'Technical - API testing and automation' }, { id: crypto.randomUUID(), date: dateStr(14), time: '03:30 PM', mode: 'offline', meetingLink: '', interviewerName: 'Lisa Ray', round: 'manager', notes: 'Manager round - team collaboration' }], qa: { ...emptyQA(), recruiterName: 'Hannah Lee', recruiterEmail: 'hannah.l@linkedin.com', applicationSource: 'linkedin', expectedSalary: '$165k', nextFollowUpDate: dateStr(7) }, activities: [addActivity('LinkedIn', 'added', 'Added LinkedIn - API Tester', 38), addActivity('LinkedIn', 'moved', 'Moved LinkedIn to Interview', 26), addActivity('LinkedIn', 'interview', 'HR round completed for LinkedIn', 26)], createdAt: ts(45), updatedAt: ts(14) }

// ─── OFFER (3) ────────────────────────────────────────────────────
const o1: Job = { id: crypto.randomUUID(), company: 'Adobe', role: 'QA Engineer', linkedinUrl: 'https://linkedin.com/jobs/adobe-qa', resume: 'qa_resume_v3.pdf', dateApplied: dateStr(50), salaryRange: '$135k - $175k', notes: 'Offer received! CTC: $155k + RSUs. Joining in 3 weeks.', status: 'offer', priority: 'urgent', timeline: makeTimeline(['applied', 'follow-up', 'interview', 'offer'], 55), interviews: [{ id: crypto.randomUUID(), date: dateStr(42), time: '11:00 AM', mode: 'online', meetingLink: 'https://adobe.hr/round', interviewerName: 'Amy Adams', round: 'hr', notes: 'HR round - expectations discussed' }, { id: crypto.randomUUID(), date: dateStr(38), time: '02:00 PM', mode: 'online', meetingLink: 'https://adobe.tech/round', interviewerName: 'Bob Chen', round: 'technical', notes: 'Technical round - passed' }, { id: crypto.randomUUID(), date: dateStr(35), time: '10:00 AM', mode: 'online', meetingLink: 'https://adobe.mgr/round', interviewerName: 'Cathy Brown', round: 'manager', notes: 'Manager round - positive' }, { id: crypto.randomUUID(), date: dateStr(32), time: '03:00 PM', mode: 'online', meetingLink: 'https://adobe.final/round', interviewerName: 'Dan Wilson', round: 'director', notes: 'Director round - culture fit' }], qa: { ...emptyQA(), recruiterName: 'Amy Adams', recruiterEmail: 'amy.a@adobe.com', applicationSource: 'linkedin', expectedSalary: '$155k', actualOfferedSalary: '$155k + RSUs' }, activities: [addActivity('Adobe', 'added', 'Added Adobe - QA Engineer', 55), addActivity('Adobe', 'moved', 'Moved Adobe to Interview', 42), addActivity('Adobe', 'moved', 'Moved Adobe to Offer', 32), addActivity('Adobe', 'interview', 'All interview rounds completed for Adobe', 32)], createdAt: ts(65), updatedAt: ts(32) }
const o2: Job = { id: crypto.randomUUID(), company: 'Salesforce', role: 'Senior QA Engineer', linkedinUrl: 'https://linkedin.com/jobs/salesforce-senior-qa', resume: 'sdet_profile_2026.pdf', dateApplied: dateStr(45), salaryRange: '$145k - $190k', notes: 'Offer received! CTC: $175k + bonus. Considering.', status: 'offer', priority: 'high', timeline: makeTimeline(['applied', 'follow-up', 'interview', 'offer'], 50), interviews: [{ id: crypto.randomUUID(), date: dateStr(38), time: '10:00 AM', mode: 'online', meetingLink: 'https://sf.hr/round', interviewerName: 'Eve Martin', round: 'hr', notes: 'HR screening' }, { id: crypto.randomUUID(), date: dateStr(34), time: '01:00 PM', mode: 'online', meetingLink: 'https://sf.tech/round', interviewerName: 'Frank Lee', round: 'technical', notes: 'Technical - Automation and frameworks' }, { id: crypto.randomUUID(), date: dateStr(30), time: '11:00 AM', mode: 'offline', meetingLink: '', interviewerName: 'Grace Kim', round: 'manager', notes: 'Manager round - leadership discussion' }], qa: { ...emptyQA(), recruiterName: 'Eve Martin', recruiterEmail: 'eve.m@salesforce.com', applicationSource: 'company_website', expectedSalary: '$175k', actualOfferedSalary: '$175k + bonus' }, activities: [addActivity('Salesforce', 'added', 'Added Salesforce - Senior QA Engineer', 50), addActivity('Salesforce', 'moved', 'Moved Salesforce to Interview', 38), addActivity('Salesforce', 'moved', 'Moved Salesforce to Offer', 30)], createdAt: ts(60), updatedAt: ts(30) }
const o3: Job = { id: crypto.randomUUID(), company: 'Infosys', role: 'QA Lead', linkedinUrl: 'https://linkedin.com/jobs/infosys-qa-lead', resume: 'lead_qa_resume.pdf', dateApplied: dateStr(40), salaryRange: '$90k - $120k', notes: 'Offer received! Good package for India location.', status: 'offer', priority: 'medium', timeline: makeTimeline(['applied', 'follow-up', 'interview', 'offer'], 40), interviews: [{ id: crypto.randomUUID(), date: dateStr(33), time: '09:30 AM', mode: 'online', meetingLink: 'https://infosys.hr/round', interviewerName: 'Ravi Kumar', round: 'hr', notes: 'HR round' }, { id: crypto.randomUUID(), date: dateStr(29), time: '02:00 PM', mode: 'online', meetingLink: 'https://infosys.tech/round', interviewerName: 'Sita Reddy', round: 'technical', notes: 'Technical round - passed' }], qa: { ...emptyQA(), recruiterName: 'Ravi Kumar', recruiterEmail: 'ravi.k@infosys.com', applicationSource: 'naukri', expectedSalary: '$105k', actualOfferedSalary: '$110k' }, activities: [addActivity('Infosys', 'added', 'Added Infosys - QA Lead', 45), addActivity('Infosys', 'moved', 'Moved Infosys to Interview', 33), addActivity('Infosys', 'moved', 'Moved Infosys to Offer', 29)], createdAt: ts(55), updatedAt: ts(29) }

// ─── REJECTED (3) ─────────────────────────────────────────────────
const r1: Job = { id: crypto.randomUUID(), company: 'Netflix', role: 'SDET', linkedinUrl: 'https://linkedin.com/jobs/netflix-sdet', resume: 'sdet_profile_2026.pdf', dateApplied: dateStr(55), salaryRange: '$200k - $300k', notes: 'Rejected after technical round. Lack of streaming domain experience.', status: 'rejected', priority: 'high', timeline: makeTimeline(['applied', 'interview', 'rejected'], 60), interviews: [{ id: crypto.randomUUID(), date: dateStr(45), time: '01:00 PM', mode: 'online', meetingLink: 'https://netflix.tech/round', interviewerName: 'James Bond', round: 'technical', notes: 'Technical round - streaming protocols knowledge needed' }], qa: { ...emptyQA(), recruiterName: 'Peter Parker', recruiterEmail: 'peter.p@netflix.com', applicationSource: 'linkedin', expectedSalary: '$250k' }, activities: [addActivity('Netflix', 'added', 'Added Netflix - SDET', 60), addActivity('Netflix', 'moved', 'Moved Netflix to Interview', 50), addActivity('Netflix', 'rejected', 'Rejected from Netflix', 55)], createdAt: ts(70), updatedAt: ts(55) }
const r2: Job = { id: crypto.randomUUID(), company: 'Accenture', role: 'QA Engineer', linkedinUrl: 'https://linkedin.com/jobs/accenture-qa', resume: 'qa_resume_v3.pdf', dateApplied: dateStr(48), salaryRange: '$85k - $110k', notes: 'Rejected after HR screening. Position filled internally.', status: 'rejected', priority: 'low', timeline: makeTimeline(['applied', 'rejected'], 55), interviews: [], qa: { ...emptyQA(), recruiterName: 'Diana Prince', recruiterEmail: 'diana.p@accenture.com', applicationSource: 'indeed', expectedSalary: '$100k' }, activities: [addActivity('Accenture', 'added', 'Added Accenture - QA Engineer', 55), addActivity('Accenture', 'rejected', 'Rejected from Accenture', 48)], createdAt: ts(60), updatedAt: ts(48) }
const r3: Job = { id: crypto.randomUUID(), company: 'Zoho', role: 'Manual Tester', linkedinUrl: 'https://linkedin.com/jobs/zoho-manual', resume: 'manual_tester_resume.pdf', dateApplied: dateStr(42), salaryRange: '$50k - $70k', notes: 'Rejected - position on hold due to budget constraints.', status: 'rejected', priority: 'low', timeline: makeTimeline(['applied', 'rejected'], 48), interviews: [], qa: { ...emptyQA(), recruiterName: 'Karthik M.', recruiterEmail: 'karthik.m@zoho.com', applicationSource: 'company_website', expectedSalary: '$60k' }, activities: [addActivity('Zoho', 'added', 'Added Zoho - Manual Tester', 48), addActivity('Zoho', 'rejected', 'Rejected from Zoho', 42)], createdAt: ts(55), updatedAt: ts(42) }

export function generateSampleData(): Job[] {
  return [w1, w2, w3, w4, w5, a1, a2, a3, a4, a5, a6, f1, f2, f3, f4, i1, i2, i3, i4, o1, o2, o3, r1, r2, r3]
}
